services:
  - type: web
    name: employee-task-app
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2
    pythonVersion: 3.11
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PORT
        value: "8000"
